-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 11, 2017 at 05:20 PM
-- Server version: 10.1.26-MariaDB
-- PHP Version: 7.1.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `kart`
--

-- --------------------------------------------------------

--
-- Table structure for table `data`
--

CREATE TABLE `data` (
  `title` varchar(255) NOT NULL,
  `description` varchar(25555) NOT NULL,
  `path` mediumtext NOT NULL,
  `price` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `data`
--

INSERT INTO `data` (`title`, `description`, `path`, `price`) VALUES
('Acer Predator', 'NVIDIA GeForce GTX 1050Ti for desktop level performance', 'https://1.bp.blogspot.com/-xdZqZyowUgc/WZ2WkVP4PvI/AAAAAAAABmg/hcUde2HSzsEz69TtjkVw6uUO5Gn_0CFQQCLcBGAs/s200/Acer%2BPredator%2BHelios%2B300%2BCore%2Bi7%2B7th%2BGen.png', 109990),
('AlienWare', 'Alienware’s most powerful 43.1 cm (17) gaming laptop is designed for VR with NVIDIA GeForce® GTX 10-Series graphics and Tobii eye tracking, taking you deeper into the game.', 'https://image3.pricedekho.com/p/3/2/42/2178042/8216898-alienware-15-mlk-r2-y569953hin9-ci716gb1tbwin10156-inch4gb-graph-aluminium-picture-big.jpg', 164991),
('Apple Macbook Air', 'MacBook Air lasts up to an incredible 12 hours between charges. So from your morning coffee to your evening commute, you can work unplugged. When it’s time to kick back and relax, you can get up to 12 hours of iTunes movie playback. And with up to 30 days of standby time, you can go away for weeks and pick up where you left off.Whatever the task, fifth-generation Intel Core i5 and i7 processors with Intel HD Graphics 6000 are up to it', 'https://smark.co.in/store/image/cache/catalog/Apple%20products/Macbook%20Air%20MMGF2HN/1-200x200.jpg', 52990),
('Apple Macbook Pro', '2.2GHz Processor 256 GB Storage 2.2GHz quad-core Intel Core i7 Turbo Boost up to 3.4GHz 16GB 1600MHz memory 256GB PCIe-based flash storage1 Intel Iris Pro Graphics - Built-in battery (9 hours)2 Force Touch trackpad', 'https://do04xel808kbz.cloudfront.net/Shopclues.com/XRVOS_shc_124354884_200x200.jpg', 137680),
('Aqua S1', '5MP primary camera with LED flash and 5MP front facing camera\r\n12.7 centimeters (5-inch) TN capacitive touchscreen with 854 x 480 pixels resolution, 196 ppi pixel density and 16.7M color support', 'http://images.buyingiq.com/p/1/1/61/2215361/9022130-intex-aqua-freedom-8gb-white-picture-big.jpg', 3999),
('Asus ROG', 'ROG Strix GL553 comes with Windows 10 pre-installed and features a 7th-generation Intel Core i7 quad-core processor, Nvdia GeForce GTX 1050 Ti graphics and full Microsoft DirectX 12 support to give you powerful performance and flawless gaming visuals. ROG Strix GL553 is made for gaming and primed for creativity. It\'s time to experience games and applications like never before. ROG Strix GL553 has a specially-designed chiclet gaming keyboard with 4-area RGB lighting and red-backlit scissor-switch keys that offer you 2.5mm of travel distance for tactile keystrokes. It also features highlighted WASD keys, so you know where your hands need to be. On top of that, a larger space bar and isolated arrow keys ensure that everything you need is kept within easy reach.', 'https://uae.microless.com/cdn/products/43983-sm.jpg', 114990),
('BPL Vivid', 'Full HD (Resolution: 1920x1080), Refresh Rate: 60 hertz', 'https://www.buyjoy.in/televisions/images/sanyoxt32s7000h32incheshdledtv250717.jpg', 21990),
('Canvas Infinity', '18:9 Full Vision display with a 5.7-inch HD IPS touchscreen and 1440 x 720 pixels resolution\r\n16MP front camera and 13MP rear camera with auto scene detection, bokeh effect, super pixel and panorama', 'http://www.mainspecs.com/wp-content/uploads/2017/09/Micromax-Canvas-Infinity-p-200x200.jpg', 9999),
('Dell Inspiron', 'First person shooter games or those massively multiplayer online games - no matter what your favourite is, with the Dell Inspiron 7567 laptop, you can enhance your gaming experience and stay ahead on the virtual battlefield as it offers a beast-like performance.', 'https://www.gizbot.com//img/200x90/img/gadget-finder/laptops/2017/09/dell-inspiron-15-7567-a542103sin8-windows-10-16gb-ram-1tb-hdd-core-i7-7th-gen-4-gb-graphic-card_1504606277.jpg', 113990),
('Eluga Ray 500', 'Display 5.50-inch Processor 1.25GHz quad-core Front Camera 5-megapixel RAM 3GB OS Android 6.0 Storage 16GB Rear Camera 13-megapixel Battery Capacity 3000mAh. A muti-tasker phone for your multitasking personality. Say Hello to the all new Eluga Pulse X and carry loads of data at the tip of your fingertips.A 3GB RAM and 16GB internal memory that is expandable up to 128GB is a catch.', 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSGG6Cc5YR7VX6SkZ2_Lr3IlhXWaLvQ87rAG8mxal_As30P3pXHFrmPb9t0lQ', 8999),
('Eluga Ray 700', 'The Panasonic Eluga Ray 700 is powered by 1.3GHz octa-core Mediatek MTK6753 processor and The phone packs 32GB of internal storage that can be expanded up to 128GB via a microSD card. As far as the cameras are concerned, the Panasonic Eluga Ray 700 packs a 13-megapixel primary camera on the rear and a 13-megapixel front shooter for selfies.', 'https://gadgets7.news/india/media/2017/09/panasonic-eluga-ray-700-gold-200x200.jpeg', 9990),
('Galaxy note 8', 'The Galaxy Note8 is your portal to a new world when connected to this range of devices and interfaces. It\'s a world where boundaries are pushed and barriers broken so you can see more, share more, and do a whole lot more-effortlessly.More screen means more space to do great things. Go big with the Galaxy Note 8\'s 16.05cm (6.3 inch) screen. It\'s the largest ever screen on a Note device and it still fits easily in your hand. ', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT_fL1WhrlcLDoVpDLND2rtnyfuq5EKiQC0wkFJjYsb1ox3wocEyILtaYR9', 67900),
('Galaxy S7', 'Samsung Galaxy S7 32GB smartphone - white offers incredible communication experience alongside insane entertainment. The dual SIM galaxy mobile runs on Quad-core (2.15GHz + 1.6GHz) Kryo processor and is based on Marshmallow Android 6.0 OS to power your needs perfectly. Storage and memory needs are met through 4GB RAM and built-in storage of 32GB with an extendable option upto 200GB via microSD slot. ', 'http://i.ebayimg.com/thumbs/images/g/X5cAAOSwKcdZvzXA/s-l200.jpg', 39990),
('Honor 6x', 'The dual lens 12MP + 2MP rear camera captures life’s magical moments in the highest definition to empower your inner photographer.\r\n\r\nNight Mode: 1.25um large pixel size for a better noise performance, even in low light\r\n\r\nSplash: An all-new splash function lets you isolate an individual color in monochrome images for greater artistic effect.\r\n\r\nHonor’s wide aperture range (F/0.95-F/16) lets you decide how much focus you want, and whether that shot calls for a stylish professional-grade blurred background effect.\r\n\r\nWith an ultra-fast focus time of 0.3 seconds, thanks to Phase Detection Auto Focus and a SONY IMX386 sensor, you will never miss that perfect picture opportunity again.\r\n\r\n', 'https://lh4.googleusercontent.com/proxy/h0g6ubyFyaTkskcj4znjkEF82iPmoG1fo-zYUYAKOAOOkVOgobD2Ra5RIid7Ay99i7j_CHm7GwxHt-Y80QlayrWm4UozvizZxOJj1N0pnspabnTI_NDnLXCJ50Towud1=w477-h308-nc', 12999),
('Honor 8', 'Honor 8 is powered by a 2.3 GHz octa-core CPU built on a 16nm architecture. 4GB of LPDDR4 RAM enables flawless multitasking and seamless gaming.\r\n\r\nThe CPU chipset contains an i5 co-processor, which controls Honor 8’s sensors and other features. The i5 co-processor works aligned with the Kirin 950 SoC chipset to increase processing speeds, response times and battery life.\r\n\r\nHonor 8 has a rapid smart file processing system for a smooth user experience.\r\n\r\n', 'https://lh4.googleusercontent.com/proxy/3kWAh_jLkmQdckw6xHnxEpB_LcbrrIzXlCivqFXHw7C7OHFw4GHN1OduxvNL1cB2w4KzDC066vbx8-CmD1oujPZ6DM_L-jD9mVsmc8LX5GsDkyzvL7si5zh4=w422-h349-nc', 14999),
('HP OMEN', 'Victory Never Comes Easy, but this laptop is ready for tha challenge.', 'https://images-eu.ssl-images-amazon.com/images/I/41AnPQUnLuL._AC_SS200_.jpg', 79900),
('iPhone 7', '12MP primary camera with optical image stabilisation, Quad-LED True Tone flash and Live Photos, 4K video recording at 30 fps and slow-motion video recording in 1080p at 120 fps, 7MP front facing FaceTime HD camera with Retina Flash', 'https://www.technobuffalo.com/wp-content/uploads/2016/09/iPhone-7-product-200x200.jpg', 42999),
('iPhone 7+', 'LED-backlit IPS LCD, capacitive touchscreen, 16M colors\r\nSize	5.5 inches, 83.4 cm2 (~67.7% screen-to-body ratio)\r\nResolution	1080 x 1920 pixels, 16:9 ratio (~401 ppi density)\r\nMultitouch	Yes', 'https://www.technobuffalo.com/wp-content/uploads/2016/09/iPhone-7-product-200x200.jpg', 60000),
('iPhone 8', 'iPhone 8 introduces an all?new glass design. The world’s most popular camera, now even better. The smartest, most powerful chip ever in a smartphone. Wireless charging that’s truly effortless. And augmented reality experiences never before possible. iPhone 8. A new generation of iPhone.', 'https://www.technobuffalo.com/wp-content/uploads/2017/09/iPhone-8-Official-Photos-05-200x200.jpg', 64000),
('iPhone SE', 'Welcome to iPhone SE, the most powerful 4?inch phone ever. To create it, we started with a beloved design, then reinvented it from the inside out. The A9 is the same advanced chip used in iPhone 6s. The 12?megapixel camera captures incredible photos and 4K videos. And Live Photos bring your images to life. The result is an iPhone that looks small. But lives large.', 'https://www.pccentre.com.na/ishoppe/image/cache/catalog/IPHONE%20SE-200x200.jpg', 19999),
('iPhone X', 'iPhone 8 introduces an all?new glass design. The world’s most popular camera, now even better. The smartest, most powerful chip ever in a smartphone. Wireless charging that’s truly effortless. And augmented reality experiences never before possible. iPhone 8. A new generation of iPhone.The most durable glass ever in a smartphone, front and back. A colour-matched, aerospace-grade aluminium band. New space grey, silver and gold finishes.', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQt-T319-83T-Xr6QS4PHjEXrqw_XWPWuLrXBNthaObHjb6gORQzA', 70999),
('J7 Prime', 'Samsung Galaxy J7 Prime Dual Sim - Black has 5.5\" screen,13 MP, f/1.9, 28mm, autofocus, LED flash, Geo-tagging, touch focus, face detection, panorama, HDR, Fingerprint, accelerometer, proximity, compass sensores, Li-Ion 3300 mAh battery, Dual SIM (Micro-SIM, dual stand-by), Android OS, v6.0.1 (Marshmallow), Octa-core 1.6 GHz Cortex-A53 CPU, microSD, up to 256 GB card slot and 16 GB, 3 GB RAM memory making it the perfect smart phone for you.', 'https://directvision.eu/image/cache/catalog/samsung-galaxy-j7-prime-sm-g610fzddins-original-imaemsfepzhsungt-200x200.jpeg', 11890),
('K8 note', 'The Lenovo K8 Note is the most power #KillerNote ever! Experience a new level of performance with a 10-core processor plus up to 4GB of RAM and 64GB of storage. K8 Note comes with 2 parallel rear cameras with 13MP and 5MP depth sensors to capture DSLR-like depth of field effect. Take amazing selfies with high resolution 13MP front camera with party flash. Enjoy an immersive multimedia experience with 13.97cm (5.5) Full HD Display with Dolby Atmos support. K8 Note ships with the stock Android 7.1.1 Nougat for a smooth and responsive experience.', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTVItUrgqdj4WuyvT63jgu_revkkW2nL_1YjDg_vp9HterInBkz9GRXI9sPHg', 11999),
('Kodak ', 'If you compare the build quality and finishing of other smart TVs available in the market, the quality of Kodak TVs is much better', 'https://cdn.shopclues.com/images/thumbnails/44092/200/200/591491823809.jpg', 22990),
('Lava X81', 'This phone comes with a large 12.7-cm HD display with IPS technology that enables you to enjoy a high-quality visual experience when you are scrolling through messages, pictures or watching videos. All, the full lamination display feature makes the screen 14% brighter that other display in direct sunlight. The 2.5 d curved glass display with corning gorilla glass 3 ensures a better viewing experience and screen protection as well.', 'https://do04xel808kbz.cloudfront.net/Amazon.in/XRVOS_amz_B01LZB4IWS_200x200.jpg', 7990),
('LeEco Le Max2', 'Qualcomm SD820 with Qualcomm Adreno 530\r\n4 GB RAM | 32 GB ROM\r\nWorld\'s First Continual Digital Lossless Audio Technology\r\nFull Metal Unibody\r\nSeamless Integration of LeEco Content\r\nUltrasonic Fingerprint Scanner\r\nType C with Quick Charge 2.0\r\n5.7 inch WQHD Display Touchscreen\r\n21 MP Primary Camera\r\n8 MP Secondary Camera\r\nDual Standby with Dual 4G Sim (LTE + LTE) and VoLTE support\r\nAndroid v6 (Marshmallow) with EUI OS', 'https://image4.geekbuying.com/make_pic/2016-07-02/LeTV-LeEco-Le-Max-2-Pro-X820-6GB-128GB-Smartphone---Fore-Gold-361523-12.jpg', 14999),
('Lenovo A6600', 'Lenovo A6600 Plus brings amazing multimedia experience with 5.0\" HD IPS Screen. Enjoy HD calls and fast downloads with VOLTE. Pure android 6.0 experience with a smoother performance and more space. 64 Bit Quadcore processor. 2GB RAM + 16GB ROM. 8MP Camera with Flash, 2300 mAh (Li-polymer) battery.', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTz5P-bcvKvmEvUeldS2xOTG5W3kk-O8aQVrs4EwVcYn7c312jl', 7499),
('Lenovo K6 Power', 'General Sales Package Handset, Charger, Wired Headset, Warranty Guide, Getting Started Guide, SIM Removal Tool Model Number K33A42 Model Name K6 Power Color Grey / Dark Grey Browse Type Smartphones SIM Type Dual Sim Hybrid Sim Slot Yes Touchscreen Yes OTG Compatible Yes Additional Content 4 GB RAM Sound Enhancements 2 x Speakers, Dolby Atmos Display Features Display Size 5 inch Resolution 1920 x 1080 Resolution Type Full HD GPU Adreno 505 at 450 MHz Other Display Features IPS Display, 5 Point Multi-touch', 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTZMCqwk03DIzXvi_eu04MR_hKgpbXvB0kQotYVClg_BhkYX5NDBLWO1p1cXA', 10790),
('Lenovo Legion', 'Enter the arena with this slim, lightweight, portable gaming PC, that easily plays your games. Powered by 7th Gen Intel® Core™ processors and up to NVIDIA GTX 1050 Ti discrete graphics, and featuring premium audio and optional hybrid storage for added speed, it’s ready for action.', 'https://www.theitdepot.com/images/proimages/200_029018.jpg', 136990),
('LG Q6', 'The latest, expansive 13.97cm(5.5) IPS Full HD+ FullVision Display gives you more to see. The 18:9 screen brings a new dimension to the smartphone viewing experience. Immerse yourself in a whole new level of videos, gaming, and browsing. A phone with smaller bezels resulting in a 18:9 Wide full screen display fits comfortably in your hands, Stunning, Seamless Design with US military standard-810G certification for durability designed to better endure impact from any direction. Most secured face recognition unlocks your phone more quickly and conveniently than ever before, without typing, drawing, swiping, or fingerprinting.', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSsok4ys1hUwoolj6d9X1M0r0qAlWaQMr7PW_k44fjAo-5CW979Pw', 12990),
('Lloyd L40S', '101.6 centimeters LED 1920 x 1080', ' https://image1.pricedekho.com/p/6/3/83/1510783/10334961-lloyd-l40s-1016-40-full-hd-smart-led-television-picture-big.jpg', 27600),
('Mi Max 2', 'Octa-core Snapdragon 625 processor, max 2.0GHz', 'https://i.ebayimg.com/thumbs/images/g/KRUAAOSwg9dZzMSb/s-l200.jpg', 16990),
('Micromax 101', 'Get a larger perspective on things with the Micromax 40\' Full HD LED TV. Once you experience its vivid and crisp details, there’s no going back to standard definition.', 'http://www.dealerservicecenter.in/assets/tv/micromax/thumb/micromax-40-canvass-full-hd-smart-101-cm-40-led-tv-3.jpeg', 21990),
('Microsoft Surface Pro 4', 'Style name:4GB, 128GB, Intel Core i5', 'https://images-eu.ssl-images-amazon.com/images/I/41s0NvamclL._AC_SS200_.jpg', 66500),
('Mitashi MiD', 'Mitashi’s M Star ACE-PROUC Engine brings you magnificent picture quality through outstanding color accuracy, visual contrast, visibility in dark areas, and sharpness in Full HD 1280 x 1024 resolution screen', 'http://www.pricedealsindia.com/pdicontent/static/images/Tv/thumbnails/mitashi24incheshdledtvmie024v10050917.jpg', 24990),
('Moto E4+', 'Motorola Moto E4 smartphone features a 5-inch HD (720p) display with 2.5D cover glass protection. The device is powered by Qualcomm\'s Snapdragon 425 quad-core processor clocked at 1.3GHz and paired with 2GB of RAM. The Moto E4 comes with 16GB of internal storage which is further expandable up to 128GB via a microSD card. In the photography department, the Moto E4 sports an 8-megapixel rear camera with autofocus and f/2.2 aperture. Up front, the smartphone houses a 5-megapixel camera with flash for selfies and video calling. The connectivity options available on the smartphone include dual-SIM support, 4G LTE, Wi-Fi, and Bluetooth. On the software front, the Moto E4 runs on Android 7.1.1 Nougat.', 'http://www.gadgetsnow.com/photo/59127462/Moto-E4-Plus.jpg', 7949),
('Moto G4 plus', 'Now get the latest Andriod 7.0 Nougat on Moto G4 and Moto G4 Plus', 'https://images-eu.ssl-images-amazon.com/images/I/81TrHL+3ogL._SS200_.jpg', 11249),
('Moto g5+', '13+13MP dual back camera (f/2.0, dual LED flash) and 8MP front facing camera with flash 4GB RAM and 64GB internal memory expandable up to 128GB 13.97cms (5.5-inch) Full HD (1080 x 1920) capacitive touchscreen with Gorilla Glass 3 protection Dual nano SIM with dual-standby (4G+4G); Metal body with fingerprint reader Android 7.1, Nougat operating system with 2.0GHz Snapdragon 625 octa-core processor 3000mAH Lithium-ion battery with 15W Turbo Charging 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including battery from the date of purchase', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTQaeuE2knmDr9keisdQR81AwI2VChbw5Makre6OesH1wBR7NWveYdeTOcUnA', 15999),
('Moto G5s', '13+13MP dual back camera (f/2.0, dual LED flash) and 8MP front facing camera with flash 4GB RAM and 64GB internal memory expandable up to 128GB 13.97cms (5.5-inch) Full HD (1080 x 1920) capacitive touchscreen with Gorilla Glass 3 protection Dual nano SIM with dual-standby (4G+4G); Metal body with fingerprint reader Android 7.1, Nougat operating system with 2.0GHz Snapdragon 625 octa-core processor 3000mAH Lithium-ion battery with 15W Turbo Charging 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including battery from the date of purchase', 'https://cdn.shopclues.com/images/thumbnails/75097/200/200/121794082P114921608881498505976.jpg', 13990),
('MSI GP', 'With the innovative Cooler Boost cooling solution and MSI’s exclusive gaming features catered for gamers, the NVIDIA\'s latest GeForce® GTX 1060 GPU releases its full performance completely on MSI gaming laptops. 3D performance of GeForce® GTX 1060 GPU is better than GeForce® GTX 970M graphics.', 'https://image3.pricedekho.com/p/3/1/71/2048771/9034423-msi-apache-pro-ge-series-ge62-core-i7-8-gb-ddr31-tb-hddwindows-103-gb-graphics-notebook-157-inch-black-picture-big.jpg', 117000),
('Nokia 105', 'The design Shaped for your palm Featuring a curved, ergonomic body and an island key layout for easier dialing and texting, the Nokia 105 gives you the feeling of a solid, quality phone nestled in the palm of your hand. It\'s good to talk The resilient battery offers up to 15 hours of talk time or a month on standby1, so you can talk from dawn until dusk. Your everyday companion The Nokia 105 is prepared for whatever the day throws at you, with its polycarbonate shell that keeps its color even when scratched. Plus, with a built-in flashlight and pre-loaded games including the classic Snake Xenzia, there\'s never a dark or dull moment.', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSRLpqrZ4-deEUbhubBns-Xg-hFaLtESJHIkHHYGcPbvXRUgUy7IYeg5VDc', 1191),
('Nokia 6', 'Nokia phones have always stood for beautiful, crafted design and excellent quality. This phone is no different: it’s built to take on life as you know it – with durable and beautiful materials and a great feel. The Nokia 6 comes with Android Nougat, the latest android. Nokia 6 comes with the full spread of Google Services and no unnecessary extras. The Nokia 6 comes with a 5.5\" full-HD display and wide color reproduction, which make it easy to enjoy your entertainment.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCnXOSapkZaz70ze-Dpk_AOf_dQdtqxsNnmhkaCB9z0JbboyFqofIscO1OXg', 14999),
('On Max', 'f/1.7 Flagship Camera | 13MP Rear Camera | 13MP Front CameraSocial Camera Mode: Instant Sharing4 GB RAM | 32 GB ROM |5.7 inch Full HD Display3300 mAh BatteryMTK P25 Lite Processor', 'https://media.samsungshop.in/catalog/product/cache/1/small_image/200x200/9df78eab33525d08d6e5fb8d27136e95/o/n/on-max-black_new.jpg', 15900),
('Oneplus 3sT', 'The OnePlus 3T stays true to our Never Settle approach. Impressive specs mean nothing if you don’t have a great experience every time you pick up your phone. The OnePlus 3T delivers the best user experience, thanks to the latest hardware upgrades and carefully tested software enhancements. It was developed with care, craftsmanship and in collaboration with our community.', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS9im6Yrxj44E8xyAPZIX-5IDFy3pJPNXgF7Gk2JPqSXDgOp3vv', 25999),
('Oneplus 3T', 'The OnePlus 3T stays true to our Never Settle approach. Impressive specs mean nothing if you don’t have a great experience every time you pick up your phone. The OnePlus 3T delivers the best user experience, thanks to the latest hardware upgrades and carefully tested software enhancements. It was developed with care, craftsmanship and in collaboration with our community.', 'https://www.technobuffalo.com/wp-content/uploads/2016/11/OnePlus-3T-poduct-200x200.jpg', 24999),
('Oneplus 5', 'The OnePlus 5 is a crazy good phone for crazy good price! The OP5 is a phone for anyone who wants a fast, capable, versatile phone with clean software and some unique features. And with a starting price of Rs 32,999 it makes so much sense. It is an all-rounder that may not have one best-in-class feature but as an overall phone, comes together very well.', 'https://www.technobuffalo.com/wp-content/uploads/2017/06/OnePlus-5-product-200x200.jpg', 32999),
('Oppo F3+', '120° Wide-Angle Camera,Dual Selfie Camera,13 MP Rear Camera,Anti-shake 2.0,Sleek Metal Body\r\n', 'https://one2shop-media.s3.amazonaws.com/catalog/product/cache/1/small_image/200x200/beff4985b56e3afdbeabfc89641a4582/o/p/oppo-f3-gold.png', 18990),
('Panasonic Viera ', 'Full HD TV with 200 Hz refresh rate make pictures look crisper and more dynamic with a wide viewing angle.', ' https://image1.pricedekho.com/p/6/6/76/1539576/7333960-panasonic-viera-th-42asm610d-10668-cm-42-inches-full-hd-smart-led-tv-black-picture-big.jpg', 26990),
('Phab 2', 'The Lenovo Phab Plus\'s 17.27cm (6.8) Full HD display with IPS technology is not just big, it\'s also clever. With a crisp 326 ppi resolution.You can do so much more with the Lenovo Phab Plus, and it\'s got the battery power to match.There\'s also a front-facing 5-megapixel wide-angle lens to help you master the art of the selfie.', 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSIBt5OK1_amQyG-UIvL-865bKVMwe2sJLEAmNMykVk-NhIrFIULc64OSEp', 13999),
('Redmi 4A', 'The new Redmi 4A is better, faster, and is possibly your best companion for both work and leisure. It packs a Snapdragon 425 64-bit, quad-core processor and a massive 3120mAh (typ)/3030mAh (min) battery that guarantees you smoother experience throughout the day. Yet it remains light - just 131.5g - and boasts a smooth matte finish that feels great in your hands. Beneath the 12.7cm (5) HD display runs MIUI 8, the latest operating system that is the most gorgeous and user-friendly operating system we\'ve introduced so far. Despite its large capacity battery, Redmi 4A stays amazingly slim and light at a mere 131.5g. It is housed in a seamless, polycarbonate body that boasts a super smooth matte finish and is to date, the lightest in the Redmi series. ', 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRFdRQIfneY5MhFt4DnEWzcWvGw6Ro3o-FN0oUpl5KG5la7-7vgG1VI8Fp7', 5999),
('Samsung Basic', 'Enjoy unlimited content and entertainment on your Samsung 100 cm (40 inches) 40M5100 Basic Smart Full HD LED TV. Connect your smartphone wireless to your TV and view on-demand content, videos, photos and listen to favourite music. Using the Smart Convergence technology and your smartphone\'s data (3G/4G/Wi-Fi), you can now cast your smartphone\'s content (YouTube, Amazon Prime, Netflix, Videos, Photos) on your TV.', 'https://static.rcwilley.com/products/110595289/Samsung-MU6300-Series-50-4K-UHD-Smart-TV-rcwilley-image1~200.jpg', 37690),
('Samsung J3 pro', 'HomeMobilesPhone FinderSamsungGalaxy J3 (6) Samsung Galaxy J3 (6) SPECIFICATIONS USER REVIEWS NEWS Galaxy J3 (6) Share on FacebookTweetShareShareEmailReddit Samsung Galaxy J3 (6) smartphone was launched in November 2015. The phone comes with a 5.00-inch touchscreen display with a resolution of 720 pixels by 1280 pixels. The Samsung Galaxy J3 (6) is powered by 1.5GHz quad-core it comes with 1.5GB of RAM. The phone packs 8GB of internal storage that can be expanded up to 128GB via a microSD card. As far as the cameras are concerned, the Samsung Galaxy J3 (6) packs a 8-megapixel primary camera on the rear and a 5-megapixel front shooter for selfies. The Samsung Galaxy J3 (6) runs Android 5.1 and is powered by a 2600mAh non removable battery. It measures 142.30 x 71.00 x 7.90 (height x width x thickness) and weighs 138.00 grams. The Samsung Galaxy J3 (6) is a single SIM (GSM) smartphone that accepts a Micro-SIM. Connectivity options include Wi-Fi, GPS, Bluetooth, NFC, FM, 3G and 4G (with support for Band 40 used by some LTE networks in India). Sensors on the phone include Proximity sensor and Accelerometer.', 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQcM9QQ2Pqh3YytaWNWWzxCR5Zg_YOjnOoujuqUmp7JyQ2FMRRn', 6490),
('Samsung on5', 'An unprecedentedly thin frame and bezel for a comfortable and steady grip. Its eye-catching, leather-feel rear cover adds an extra touch of class.', 'https://image2.pricedekho.com/p/1/1/91/2321391/10340147-samsung-galaxy-on5-pro-black-picture-big.jpg', 7490),
('Samsung on7', 'Surf like a pro,Game like a pro,Ride like a pro', 'https://image3.pricedekho.com/p/1/0/90/2238290/10340099-samsung-galaxy-on7-pro-gold-picture-big.jpg', 8990),
('Sony Bravia ', 'Switch on to Sony full HD 1080p and experience sharper, clearer, more colourful pictures with five times the detail of standard definition TV. The new smartphone plug and play feature lets you enjoy all your smartphone contents with better picture and sound quality. Your TV is safeguarded against dust, lightning surges and humidity with X-Protection Pro and ready to entertain with features like FM radio and USB multi-format play.', ' https://www.avechi.com/wp-content/uploads/2017/02/SONY-55-Smart-4K-Digital-Full-HD-LED-Tv-..Android-Tv-x-reality-PRO-200x200.jpg', 41499),
('Vibe K5 Note', 'The phone combines brilliant performance with bargain pricing. Designed for multimedia enthusiasts on a budget, this lightweight smartphone offers 5-inch wide view HD displays for rich, smooth videos. 4G LTE connectivity and an optional octa-core processor deliver blazing speeds for the latest games. Dolby Atmos enhances the whole experience with dynamic sound.', 'https://image2.pricedekho.com/p/1/6/66/2174866/10055834-lenovo-vibe-k5-note-3gb-ram-silver-picture-big.jpg', 7999),
('Vivo V7+', 'This smartphone runs on Qualcomm Snapdragon 450 processor. This processor improves the overall user experience of the phone. It is based on the Android 7.1.2 Nougat operating system, which again has multiple features that improve the overall user experience. Vivo has added their own FunTouch 3.2 OS to the Android OS and improved the user experience of the device.', 'https://b6c18f286245704fe3e9-05e2055f4cd9122af02914269431c9f6.ssl.cf1.rackcdn.com/18152840_vivo-v7-plus-launches-officially-in_cec26446_m.jpg?bg=C4BDCB', 21990),
('YU Yureka 2', 'The Yureka Plus has over 2 million pixels, giving you mind blowing clarity and sharpness 1920X1080 Full HD resolution. Get ready to have your retinas rocked Capture exquisite shots from the 13 MP camera. Snap pictures or videos right from the lockscreen and pause time with slo-mo to relive every moment Power your applications with up to 8 times faster processing. The 2 GB RAM is an accelerated DDR3 variant which when combined with the Snapdragon 615 64 bit processor makes for a perfect combination, giving you a full 100% efficiency.', 'https://lh3.googleusercontent.com/proxy/DqiGXCoP-Kw2ZFeQDq0YTzNR3LCPHZ3_caYoLi0eGf_ISZnA5i213s4SP0lAGBNpvgeXo7nROh_W3pVqDKLktYkPKc2hOt6hLF1DYlDLG5-R6AAUszttvUFHl0PPHMxb51vHK4pJg3Mclrb6fqsqVbCzQPBa-ZB7ynFSann6nsga7WtG4fCv=w350-h200-nc', 7500),
('Z2 plus', 'Z2 Plus is powered by the Qualcomm’s flagship process - Snapdragon 820, providing ultimate power, graphics, connectivity, photography and battery efficiency. We have activated all the aspects of SoC - DSP, ISP, Modems and Sensor Processing Unit (SPU) to truly provide a flagship experience.', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSdhcyF_f3S66gdKCXr9hcGMwNLz58v0bs1ipdnHRxb12QmhqCsclE7gZhxkQ', 10499),
('Zenphone 4', 'Zenfone 3 is an agile, exquisite design inspired by the beauty of nature. A glass and metal wonder that captures the world with absolute clarity. An extraordinary smartphone for a life less ordinary.', 'https://imei24.com/img/asus/17_46_22_Asus_Zenfone_4.jpg', 17990);

-- --------------------------------------------------------

--
-- Table structure for table `login`
--

CREATE TABLE `login` (
  `username` varchar(255) NOT NULL,
  `password` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `login`
--

INSERT INTO `login` (`username`, `password`) VALUES
('admin', 'admin'),
('123', '123'),
('1233', '12'),
('jatin', '12345'),
('jatinparab', '123456'),
('jatin12345', '12345'),
('test123', 'test123');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `data`
--
ALTER TABLE `data`
  ADD UNIQUE KEY `title` (`title`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
